[package]
name = "dl_alexandria_utils"
version = "0.2.0"
description = "Cairo utilities"
homepage = "https://github.com/Digine-Labs/alexandria/tree/0.2.0/packages/utils/src"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true
