[package]
name = "alexandria_ascii"
description = "utilities for working with ascii values"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/ascii"
edition = "2023_11"
version.workspace = true

[tool]
fmt.workspace = true

[dependencies]
alexandria_data_structures = { path = "../data_structures", version = "0.2.0" }

[dev-dependencies]
cairo_test.workspace = true